- name: ensure file {{ item.value.dest }} exists
  copy:
    content: ""
    dest: "/etc/security/limits.d/{{ item.value.dest }}"
    force: no
    mode: 0644
  with_dict: "{{ pam_limits_limits }}"

- pam_limits:
    dest: "/etc/security/limits.d/{{ item.value.dest }}"
    domain: "{{ item.value.domain }}"
    limit_type: "{{ item.value.type }}"
    limit_item: "{{ item.value.item }}"
    value: "{{ item.value.value }}"
    comment: "{{ item.value.comment | default('') }}"
  with_dict: "{{ pam_limits_limits }}"
